name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.LICENSE_TOKEN }}
        run: make license-check

      - name: Run verification
        run: make check

      - name: Test
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
          FUNCTION_REGION: ${{ secrets.FUNCTION_REGION }}
        run: test/e2e_test.sh
