name: oidc

on:
  push:
    branches: [ "oidc_test" ]


jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()   
            coredemo.setOutput('id_token', id_token)
            console.log(id_token)
  job2:
    runs-on: ubuntu-latest
    needs: job
    steps:
      - run: echo ${{needs.job.outputs.id_token}}