name: oidc

on:
  push:
    branches: [ "oidc_test" ]


jobs:
  job:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#
#      - name: Build
#        run: go build -v ./...

      #      - name: Check licenses
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.LICENSE_TOKEN }}
      #        run: make license-check
      #
      #      - name: Run verification
      #        run: make check
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: step_one1
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()   
            coredemo.setOutput('id_token', id_token)
            console.log(id_token)
      - name: Test
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
          FUNCTION_REGION: ${{ secrets.FUNCTION_REGION }}
          jwt_token: ${{ steps.step_one1.outputs.id_token }}
        run: test/e2e_test.sh