name: oidc

on:
  push:
    branches: [ "oidc_test" ]


jobs:
  permissions:
    id-token: write

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#
#      - name: Build
#        run: go build -v ./...

      #      - name: Check licenses
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.LICENSE_TOKEN }}
      #        run: make license-check
      #
      #      - name: Run verification
      #        run: make check

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()   
            coredemo.setOutput('id_token', id_token)
            console.log(id_token)
      - name: asddase
        id: step_one2
        run: |
          echo "::set-output name=test::hello"
      - name: Set the value
        id: step_one
        run: |
          echo "dsaadasdasdadssd :  ${{ steps.idtoken.outputs.test }}"
