name: Pre-test

on:
  pull_request_review:
    types: [submitted]

jobs:
  pre-test:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    name: pre-test-step
    steps:
      - name: Explanation
        run: echo "pre-test step run success"