name: presubmits

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Build
        run: go build -v ./...

  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

      - name: Run verification
        run: make check

  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Install required packages
        run: npm install @actions/core@1.6.0 @actions/http-client uuid@^3.3.3

      - name: Generate uuid
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        id: get_uuid
        with:
          script: |
            const coredemo = require('@actions/core')
            const uuid = require('uuid/v1')
            let uuidVal = uuid()
            coredemo.setOutput('uuid', uuidVal)

      - name: Test
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
          FUNCTION_REGION: ${{ secrets.FUNCTION_REGION }}
          jwt_token: ${{ steps.get_id_token.outputs.id_token }}
          COSIGN_EXPERIMENTAL: 0
          is_start: true
          uuid: ${{ steps.get_uuid.outputs.uuid }}
        run: test/e2e_test.sh

      - name: Get IdToken
        if: always()
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        id: get_id_token
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken("sigstore")   
            coredemo.setOutput('id_token', id_token)

      - name: KeylessTest
        if: always()
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
          FUNCTION_REGION: ${{ secrets.FUNCTION_REGION }}
          jwt_token: ${{ steps.get_id_token.outputs.id_token }}
          COSIGN_EXPERIMENTAL: 1
          is_start: false
          uuid: ${{ steps.get_uuid.outputs.uuid }}
        run: test/e2e_test_keyless.sh
